### ISSUE TITLE
2021-11-9: Translate header/footer items

### ISSUE THREAD

**Issue by jayhill** [CodeForAsheville/court-notifications#94]
Header items `Home` and `Tips` and footer items `Contact` and `Privacy Policy` should be localized to the selected language.

We can get help doing the translations themselves, but it would be great to add the key and English to the translation files.

![image](https://user-images.githubusercontent.com/116148/140964265-09b3b195-b2c0-4d59-bc1d-5b2756a5e7b5.png)
![image](https://user-images.githubusercontent.com/116148/140964273-157f182f-dd59-43f4-8075-81ad095c573a.png)

**Comment by ejaxon** [comment]
Added translations for the footer. Waiting until Colin merges in changes for the menu and routing before I take on the menu translation

**Comment by Yovaxox** [comment]
It seems that header items such as `Home` and `Tips` aren't translating to Spanish or Russian, even if the translate file is correct.

In addition, I would correct these texts in Spanish (it's in the `Tips` section):

![image](https://user-images.githubusercontent.com/77306517/178597398-bf6b2ab0-fa3e-4017-becc-93985a037241.png)

Instead of "Vístase en forma respetuosa" is "Vístase de forma respetuosa.".

Instead of "Si faltas tu cita" is "Si falta a su cita".

Pd. I'm new, I'm was studying this project, so I'll try to fix it soon if I can.

**Comment by jayhill** [comment]
Thank you, @Yovaxox! 🎉

**Comment by ejaxon** [comment]
Good catch, @Yovaxox! 

If you figure out how to fix it and do a pull request, that's great. Or I can make the changes this weekend.
